import sys, os, csv

from org.opentreeoflife.taxa import Taxonomy, SourceTaxonomy, Taxon
from org.opentreeoflife.smasher import UnionTaxonomy

dwh = UnionTaxonomy.newTaxonomy('dwh')

#Use this to tell smasher what separation file to use
dwh.setSkeleton(Taxonomy.getTaxonomy('tax/separation/', 'separation'))

# 1. trunk
# 2. ictv
# 3. IOC
# 4. ASW
# 5. ODO
# 6. BOM
# 7. ERE
# 8. ONY
# 9. EET
# 10. NCBI
# 11. WOR
# 12. CLP
# 13. COL

#use this to load the taxonomies

trunk = Taxonomy.getTaxonomy('t/tax_2018_12/trunk/', 'trunk')
ictv = Taxonomy.getTaxonomy('t/tax_2018_12/ictv/', 'ictv')
IOC = Taxonomy.getTaxonomy('t/tax_2018_12/IOC/', 'IOC')
ASW = Taxonomy.getTaxonomy('t/tax_2018_12/ASW/', 'ASW')
ODO = Taxonomy.getTaxonomy('t/tax_2018_12/ODO/', 'ODO')
BOM = Taxonomy.getTaxonomy('t/tax_2018_12/BOM/', 'BOM')
ERE = Taxonomy.getTaxonomy('t/tax_2018_12/ERE/', 'ERE')
ONY = Taxonomy.getTaxonomy('t/tax_2018_12/ONY/', 'ONY')
EET = Taxonomy.getTaxonomy('t/tax_2018_12/EET/', 'EET')
NCBI = Taxonomy.getTaxonomy('t/tax_2018_12/NCBI/', 'NCBI')
WOR = Taxonomy.getTaxonomy('t/tax_2018_12/WOR/', 'WOR')
CLP = Taxonomy.getTaxonomy('t/tax_2018_12/CLP/', 'CLP')
COL = Taxonomy.getTaxonomy('t/tax_2018_12/COL/', 'COL')

#Use this to absorb one taxonomy into another

alignment = dwh.alignment(trunk)
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(ictv)
alignment.same(ictv.taxon("Viruses"), dwh.taxon("Viruses"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(IOC)
alignment.same(IOC.taxon("Neornithes"), dwh.taxon("Neornithes"))
alignment.same(IOC.taxon("Paleognathae"), dwh.taxon("Palaeognathae"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(ASW)
alignment.same(ASW.taxon("Amphibia"), dwh.taxon("Lissamphibia"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(ODO)
alignment.same(ODO.taxon("Odonata"), dwh.taxon("Odonata"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(BOM)
alignment.same(BOM.taxon("Bombycoidea"), dwh.taxon("Bombycoidea"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(ERE)
alignment.same(ERE.taxon("Erebidae"), dwh.taxon("Erebidae"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(ONY)
alignment.same(ONY.taxon("Onychophora"), dwh.taxon("Onychophora"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(EET)
alignment.same(EET.taxon("Crassiclitellata"), dwh.taxon("Crassiclitellata"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(NCBI)
alignment.same(NCBI.taxon("Actinophryidae"), dwh.taxon("Actinophryida"))
alignment.same(NCBI.taxon("Alveolata"), dwh.taxon("Alveolata"))
alignment.same(NCBI.taxon("Amoebozoa"), dwh.taxon("Amoebozoa"))
alignment.same(NCBI.taxon("Archaea"), dwh.taxon("Archaea"))
alignment.same(NCBI.taxon("Archamoebae"), dwh.taxon("Archamoebea"))
alignment.same(NCBI.taxon("Ascetosporea"), dwh.taxon("Ascetosporea"))
alignment.same(NCBI.taxon("Aurearenophyceae"), dwh.taxon("Aurearenophyceae"))
alignment.same(NCBI.taxon("Bacteria"), dwh.taxon("Bacteria"))
alignment.same(NCBI.taxon("Bolidophyceae"), dwh.taxon("Bolidophyceae"))
alignment.same(NCBI.taxon("Breviatea"), dwh.taxon("Breviatea"))
alignment.same(NCBI.taxon("cellular organisms"), dwh.taxon("Cellular Organisms"))
alignment.same(NCBI.taxon("Centroheliozoa"), dwh.taxon("Centroplasthelida"))
alignment.same(NCBI.taxon("Cercozoa"), dwh.taxon("Cercozoa"))
alignment.same(NCBI.taxon("Chlorarachniophyceae"), dwh.taxon("Chlorarachnea"))
alignment.same(NCBI.taxon("Choanoflagellida"), dwh.taxon("Choanoflagellata"))
alignment.same(NCBI.taxon("Synurophyceae"), dwh.taxon("Chrysophyceae"))
alignment.same(NCBI.taxon("Ciliophora"), dwh.taxon("Ciliophora"))
alignment.same(NCBI.taxon("Cryptophyta"), dwh.taxon("Cryptophyta"))
alignment.same(NCBI.taxon("Dactylopodida"), dwh.taxon("Dactylopodida"))
alignment.same(NCBI.taxon("Dermamoebida"), dwh.taxon("Dermamoebida"))
alignment.same(NCBI.taxon("Developea"), dwh.taxon("Developea"))
alignment.same(NCBI.taxon("Bacillariophyta"), dwh.taxon("Diatomeae"))
alignment.same(NCBI.taxon("Dictyostelids"), dwh.taxon("Dictyostelids"))
alignment.same(NCBI.taxon("Discosea"), dwh.taxon("Discosea"))
alignment.same(NCBI.taxon("Ebriidae"), dwh.taxon("Ebriaceae"))
alignment.same(NCBI.taxon("Euamoebida"), dwh.taxon("Euamoebida"))
alignment.same(NCBI.taxon("Euglenozoa"), dwh.taxon("Euglenozoa"))
alignment.same(NCBI.taxon("Eukaryota"), dwh.taxon("Eukaryota"))
alignment.same(NCBI.taxon("Mycetozoa"), dwh.taxon("Eumycetozoa"))
alignment.same(NCBI.taxon("Eustigmatophyceae"), dwh.taxon("Eustigmatophyceae"))
alignment.same(NCBI.taxon("Flabellinia"), dwh.taxon("Flabellinia"))
alignment.same(NCBI.taxon("Fornicata"), dwh.taxon("Fornicata"))
alignment.same(NCBI.taxon("Glaucocystophyceae"), dwh.taxon("Glaucophyta"))
alignment.same(NCBI.taxon("Granofilosea"), dwh.taxon("Granofilosea"))
alignment.same(NCBI.taxon("Guttulinaceae"), dwh.taxon("Guttulinopsidae"))
alignment.same(NCBI.taxon("Haptophyceae"), dwh.taxon("Haptophyta"))
alignment.same(NCBI.taxon("Hyphochytriomycetes"), dwh.taxon("Hyphochytrea"))
alignment.same(NCBI.taxon("Eccrinales"), dwh.taxon("Ichthyophonida"))
alignment.same(NCBI.taxon("Imbricatea"), dwh.taxon("Imbricatea"))
alignment.same(NCBI.taxon("Jakobida"), dwh.taxon("Jakobida"))
alignment.same(NCBI.taxon("root"), dwh.taxon("Life"))
alignment.same(NCBI.taxon("Myxogastria"), dwh.taxon("Myxogastria"))
alignment.same(NCBI.taxon("Slopalinida"), dwh.taxon("Opalinata"))
alignment.same(NCBI.taxon("Opisthokonta"), dwh.taxon("Opisthokonta"))
alignment.same(NCBI.taxon("Pansomonadida"), dwh.taxon("Pansomonadida"))
alignment.same(NCBI.taxon("Parabasalia"), dwh.taxon("Parabasalia"))
alignment.same(NCBI.taxon("Perkinsea"), dwh.taxon("Perkinsea"))
alignment.same(NCBI.taxon("Phaeodarea"), dwh.taxon("Phaeodarea"))
alignment.same(NCBI.taxon("Phaeophyceae"), dwh.taxon("Phaeophyceae"))
alignment.same(NCBI.taxon("Pinguiophyceae"), dwh.taxon("Pinguiophyceae"))
alignment.same(NCBI.taxon("Plasmodiophorida"), dwh.taxon("Plasmodiophorida"))
alignment.same(NCBI.taxon("Rhizaria"), dwh.taxon("Rhizaria"))
alignment.same(NCBI.taxon("Rhodophyta"), dwh.taxon("Rhodophyta"))
alignment.same(NCBI.taxon("Nucleariidae and Fonticula group"), dwh.taxon("Rotosphaerida"))
alignment.same(NCBI.taxon("Stramenopiles"), dwh.taxon("Stramenopiles"))
alignment.same(NCBI.taxon("Stygamoebida"), dwh.taxon("Stygamoebida"))
alignment.same(NCBI.taxon("Thecamoebida"), dwh.taxon("Thecamoebida"))
alignment.same(NCBI.taxon("Thecofilosea"), dwh.taxon("Thecofilosea"))
alignment.same(NCBI.taxon("Tubulinea"), dwh.taxon("Tubulinea"))
alignment.same(NCBI.taxon("Protosteliales"), dwh.taxon("Variosea"))
alignment.same(NCBI.taxon("Ventricleftida"), dwh.taxon("Ventricleftida"))
alignment.same(NCBI.taxon("Xanthophyceae"), dwh.taxon("Xanthophyceae"))
alignment.same(NCBI.taxon("Oomycetes"), dwh.taxon("Gyrista"))
alignment.same(NCBI.taxon("X-cell parasites"), dwh.taxon("X-cell parasites"))
alignment.same(NCBI.taxon("Kinetoplastida"), dwh.taxon("Kinetoplastida"))
alignment.same(NCBI.taxon("Viannia"), dwh.taxon("Leishmania (Viannia)"))
alignment.same(NCBI.taxon("Leishmania"), dwh.taxon("Leishmania (Leishmania)"))
alignment.same(NCBI.taxon("Trypanozoon"), dwh.taxon("Trypanosoma (Trypanozoon)"))
alignment.same(NCBI.taxon("Herpetosoma"), dwh.taxon("Trypanosoma (Herpetosoma)"))
alignment.same(NCBI.taxon("Nannomonas"), dwh.taxon("Trypanosoma (Nannomonas)"))
alignment.same(NCBI.taxon("Schizotrypanum"), dwh.taxon("Trypanosoma (Schizotrypanum)"))
alignment.same(NCBI.taxon("Duttonella"), dwh.taxon("Trypanosoma (Duttonella)"))
alignment.same(NCBI.taxon("Mundinia"), dwh.taxon("Leishmania (Mundinia)"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(WOR)
alignment.same(WOR.taxon("Acantharia"), dwh.taxon("Acantharea"))
alignment.same(WOR.taxon("Alveolata"), dwh.taxon("Alveolata"))
alignment.same(WOR.taxon("Apicomplexa"), dwh.taxon("Apicomplexa"))
alignment.same(WOR.taxon("Apusomonadidae"), dwh.taxon("Apusomonadidae"))
alignment.same(WOR.taxon("Bacteria"), dwh.taxon("Bacteria"))
alignment.same(WOR.taxon("Bicoecida"), dwh.taxon("Bicosoecida"))
alignment.same(WOR.taxon("Bigyra"), dwh.taxon("Bigyra"))
alignment.same(WOR.taxon("Centrohelida"), dwh.taxon("Centroplasthelida"))
alignment.same(WOR.taxon("Choanoflagellatea"), dwh.taxon("Choanoflagellata"))
alignment.same(WOR.taxon("Ciliophora"), dwh.taxon("Ciliophora"))
alignment.same(WOR.taxon("Colponemea"), dwh.taxon("Colponemidia"))
alignment.same(WOR.taxon("Crinoidea"), dwh.taxon("Crinoidea"))
alignment.same(WOR.taxon("Cryptophyta"), dwh.taxon("Cryptophyta"))
alignment.same(WOR.taxon("Bigyromonadea"), dwh.taxon("Developea"))
alignment.same(WOR.taxon("Bacillariophyceae"), dwh.taxon("Diatomeae"))
alignment.same(WOR.taxon("Khakista"), dwh.taxon("Diatomista"))
alignment.same(WOR.taxon("Dinoflagellata"), dwh.taxon("Dinoflagellata"))
alignment.same(WOR.taxon("Jakobea"), dwh.taxon("Discoba"))
alignment.same(WOR.taxon("Discosea"), dwh.taxon("Discosea"))
alignment.same(WOR.taxon("Echinamoebida"), dwh.taxon("Echinamoebida"))
alignment.same(WOR.taxon("Endomyxa"), dwh.taxon("Endomyxa"))
alignment.same(WOR.taxon("Enteromonadidae"), dwh.taxon("Enteromonadidae"))
alignment.same(WOR.taxon("Euglenozoa"), dwh.taxon("Euglenozoa"))
alignment.same(WOR.taxon("Euglenozoa"), dwh.taxon("Euglenozoa"))
alignment.same(WOR.taxon("Flabellinia"), dwh.taxon("Flabellinia"))
alignment.same(WOR.taxon("Glaucophyta"), dwh.taxon("Glaucophyta"))
alignment.same(WOR.taxon("Haptophyta"), dwh.taxon("Haptophyta"))
alignment.same(WOR.taxon("Heterolobosea"), dwh.taxon("Heterolobosea"))
alignment.same(WOR.taxon("Hexamitidae"), dwh.taxon("Hexamitidae"))
alignment.same(WOR.taxon("Ichthyosporea"), dwh.taxon("Ichthyosporea"))
alignment.same(WOR.taxon("Labyrinthulea"), dwh.taxon("Labyrinthulomycetes"))
alignment.same(WOR.taxon("Malawimonadea"), dwh.taxon("Malawimonadidae"))
alignment.same(WOR.taxon("Ministeriida"), dwh.taxon("Ministeria"))
alignment.same(WOR.taxon("Opalinata"), dwh.taxon("Opalinata"))
alignment.same(WOR.taxon("Opalozoa"), dwh.taxon("Opalozoa"))
alignment.same(WOR.taxon("Oxymonadida"), dwh.taxon("Oxymonadida"))
alignment.same(WOR.taxon("Parabasalia"), dwh.taxon("Parabasalia"))
alignment.same(WOR.taxon("Phaeodaria"), dwh.taxon("Phaeodarea"))
alignment.same(WOR.taxon("Placidiida"), dwh.taxon("Placididea"))
alignment.same(WOR.taxon("Polycystina"), dwh.taxon("Polycystinea"))
alignment.same(WOR.taxon("Radiozoa"), dwh.taxon("Radiolaria"))
alignment.same(WOR.taxon("Rhizaria"), dwh.taxon("Rhizaria"))
alignment.same(WOR.taxon("Rhodophyta"), dwh.taxon("Rhodophyta"))
alignment.same(WOR.taxon("Nucleariida"), dwh.taxon("Rotosphaerida"))
alignment.same(WOR.taxon("Rozellidae"), dwh.taxon("Rozellidae"))
alignment.same(WOR.taxon("Sagenista"), dwh.taxon("Sagenista"))
alignment.same(WOR.taxon("Heterokonta"), dwh.taxon("Stramenopiles"))
alignment.same(WOR.taxon("Tubulinea"), dwh.taxon("Tubulinea"))
alignment.same(WOR.taxon("Eccrinales"), dwh.taxon("Ichthyophonida"))
alignment.same(WOR.taxon("Oomycota"), dwh.taxon("Gyrista"))
alignment.same(WOR.taxon("Ctenophora"), dwh.taxon("Ctenophora"))
alignment.same(WOR.taxon("Ctenophora"), dwh.taxon("Ctenophora"))
alignment.same(WOR.taxon("Diplura"), dwh.taxon("Diplura"))
alignment.same(WOR.taxon("Vertebrata"), dwh.taxon("Vertebrata"))
alignment.same(WOR.taxon("Chroodactylon"), dwh.taxon("Chroodactylon"))
alignment.same(WOR.taxon("Clathromorphum"), dwh.taxon("Clathromorphum"))
alignment.same(WOR.taxon("Coleodesmium"), dwh.taxon("Coleodesmium"))
alignment.same(WOR.taxon("Diplonema"), dwh.taxon("Diplonema"))
alignment.same(WOR.taxon("Lejolisia"), dwh.taxon("Lejolisia"))
alignment.same(WOR.taxon("Thermotogae"), dwh.taxon("Thermotogae"))
alignment.same(WOR.taxon("Actinobacteria"), dwh.taxon("Actinobacteria"))
alignment.same(WOR.taxon("Actinobacteria"), dwh.taxon("Actinobacteria"))
alignment.same(WOR.taxon("Elusimicrobia"), dwh.taxon("Elusimicrobia"))
alignment.same(WOR.taxon("Gemmatimonadetes"), dwh.taxon("Gemmatimonadetes"))
alignment.same(WOR.taxon("Chlamydiae"), dwh.taxon("Chlamydiae"))
alignment.same(WOR.taxon("Acidobacteria"), dwh.taxon("Acidobacteria"))
alignment.same(WOR.taxon("Kinetoplastea"), dwh.taxon("Kinetoplastida"))
alignment.same(WOR.taxon("Fredericqia"), dwh.taxon("Fredericqia"))
alignment.same(WOR.taxon("Zanardinia"), dwh.taxon("Zanardinia"))
alignment.same(WOR.taxon("Tabularia"), dwh.taxon("Tabularia"))
alignment.same(WOR.taxon("Phyllobacteriaceae"), dwh.taxon("Phyllobacteriaceae"))
alignment.same(WOR.taxon("Spongopyle"), dwh.taxon("Spongopyle"))
alignment.same(WOR.taxon("Eucyrtidium"), dwh.taxon("Eucyrtidium"))
alignment.same(WOR.taxon("Stylodictya"), dwh.taxon("Stylodictya"))
alignment.same(WOR.taxon("Spongodiscus"), dwh.taxon("Spongodiscus"))
alignment.same(WOR.taxon("Hexacontium"), dwh.taxon("Hexacontium"))
alignment.same(WOR.taxon("Dictyocoryne"), dwh.taxon("Dictyocoryne"))
alignment.same(WOR.taxon("Ceratospyris"), dwh.taxon("Ceratospyris"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(CLP)
alignment.same(CLP.taxon("Amoebidiidae"), dwh.taxon("Amoebidiaceae"))
alignment.same(CLP.taxon("Chaetocerotaceae"), dwh.taxon("Chaetocerotaceae"))
alignment.same(CLP.taxon("Ciliophora"), dwh.taxon("Ciliophora"))
alignment.same(CLP.taxon("Bigyromonadea"), dwh.taxon("Developea"))
alignment.same(CLP.taxon("Dictyosteliomycetes"), dwh.taxon("Dictyostelids"))
alignment.same(CLP.taxon("Eccriniidae"), dwh.taxon("Eccrinaceae"))
alignment.same(CLP.taxon("Mycetozoa"), dwh.taxon("Eumycetozoa"))
alignment.same(CLP.taxon("Myxomycetes"), dwh.taxon("Myxogastria"))
alignment.same(CLP.taxon("Protosteliomycetes"), dwh.taxon("Variosea"))
alignment.same(CLP.taxon("Eccrinida"), dwh.taxon("Ichthyophonida"))
alignment.same(CLP.taxon("Microsporidia"), dwh.taxon("Microsporidia"))
alignment.same(CLP.taxon("Naviculaceae"), dwh.taxon("Naviculaceae"))
alignment.same(CLP.taxon("Oomycota"), dwh.taxon("Gyrista"))
alignment.same(CLP.taxon("Polycystina"), dwh.taxon("Polycystinea"))
alignment.same(CLP.taxon("Bryophyllum"), dwh.taxon("Bryophyllum"))
alignment.same(CLP.taxon("Spongopyle"), dwh.taxon("Spongopyle"))
alignment.same(CLP.taxon("Spirocyrtis"), dwh.taxon("Spirocyrtis"))
alignment.same(CLP.taxon("Siphocampe"), dwh.taxon("Siphocampe"))
alignment.same(CLP.taxon("Eucyrtidium"), dwh.taxon("Eucyrtidium"))
alignment.same(CLP.taxon("Tetraplecta"), dwh.taxon("Tetraplecta"))
alignment.same(CLP.taxon("Theocorys"), dwh.taxon("Theocorys"))
alignment.same(CLP.taxon("Stylosphaera"), dwh.taxon("Stylosphaera"))
alignment.same(CLP.taxon("Stylodictya"), dwh.taxon("Stylodictya"))
alignment.same(CLP.taxon("Spongodiscus"), dwh.taxon("Spongodiscus"))
alignment.same(CLP.taxon("Octodendron"), dwh.taxon("Octodendron"))
alignment.same(CLP.taxon("Lophocyrtis"), dwh.taxon("Lophocyrtis"))
alignment.same(CLP.taxon("Lithostrobus"), dwh.taxon("Lithostrobus"))
alignment.same(CLP.taxon("Lithocampe"), dwh.taxon("Lithocampe"))
alignment.same(CLP.taxon("Hexastylus"), dwh.taxon("Hexastylus"))
alignment.same(CLP.taxon("Hexacontium"), dwh.taxon("Hexacontium"))
alignment.same(CLP.taxon("Haliomma"), dwh.taxon("Haliomma"))
alignment.same(CLP.taxon("Dictyophimus"), dwh.taxon("Dictyophimus"))
alignment.same(CLP.taxon("Dictyocoryne"), dwh.taxon("Dictyocoryne"))
alignment.same(CLP.taxon("Dendrospyris"), dwh.taxon("Dendrospyris"))
alignment.same(CLP.taxon("Cornutella"), dwh.taxon("Cornutella"))
alignment.same(CLP.taxon("Ceratospyris"), dwh.taxon("Ceratospyris"))
alignment.same(CLP.taxon("Calocyclas"), dwh.taxon("Calocyclas"))
alignment.same(CLP.taxon("Bathropyramis"), dwh.taxon("Bathropyramis"))
alignment.same(CLP.taxon("Amphisphaera"), dwh.taxon("Amphisphaera"))
alignment.same(CLP.taxon("Vorticella dudekemi"), dwh.taxon("Vorticella dudekemi"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

alignment = dwh.alignment(COL)
alignment.same(COL.taxon("Hemitripteridae"), dwh.taxon("Agonidae"))
alignment.same(COL.taxon("Leptochilichthyidae"), dwh.taxon("Alepocephalidae"))
alignment.same(COL.taxon("Saccopharyngiformes"), dwh.taxon("Anguilliformes"))
alignment.same(COL.taxon("Arctiidae"), dwh.taxon("Arctiinae"))
alignment.same(COL.taxon("Hydnoraceae"), dwh.taxon("Aristolochiaceae"))
alignment.same(COL.taxon("Astigmata"), dwh.taxon("Astigmata"))
alignment.same(COL.taxon("Notocheiridae"), dwh.taxon("Atherinopsidae"))
alignment.same(COL.taxon("Holcopogonidae"), dwh.taxon("Autostichidae"))
alignment.same(COL.taxon("Symmocidae"), dwh.taxon("Autostichidae"))
alignment.same(COL.taxon("Olyridae"), dwh.taxon("Bagridae"))
alignment.same(COL.taxon("Bolyeridae"), dwh.taxon("Bolyeriidae"))
alignment.same(COL.taxon("Codonaceae"), dwh.taxon("Boraginaceae"))
alignment.same(COL.taxon("Ehretiaceae"), dwh.taxon("Boraginaceae"))
alignment.same(COL.taxon("Wellstediaceae"), dwh.taxon("Boraginaceae"))
alignment.same(COL.taxon("Heliotropiaceae"), dwh.taxon("Boraginaceae"))
alignment.same(COL.taxon("Hydrophyllaceae"), dwh.taxon("Boraginaceae"))
alignment.same(COL.taxon("Didymelaceae"), dwh.taxon("Buxaceae"))
alignment.same(COL.taxon("Aphyonidae"), dwh.taxon("Bythitidae"))
alignment.same(COL.taxon("Latidae"), dwh.taxon("Centropomidae"))
alignment.same(COL.taxon("Artiodactyla"), dwh.taxon("Cetartiodactyla"))
alignment.same(COL.taxon("Axiidae"), dwh.taxon("Cimeliidae"))
alignment.same(COL.taxon("Dussumieriidae"), dwh.taxon("Clupeidae"))
alignment.same(COL.taxon("Collembola"), dwh.taxon("Collembola"))
alignment.same(COL.taxon("Abyssocottidae"), dwh.taxon("Cottidae"))
alignment.same(COL.taxon("Comephoridae"), dwh.taxon("Cottidae"))
alignment.same(COL.taxon("Cottocomephoridae"), dwh.taxon("Cottidae"))
alignment.same(COL.taxon("Cyprinodontiformes"), dwh.taxon("Cyprinodontiformes"))
alignment.same(COL.taxon("Ethmiidae"), dwh.taxon("Depressariidae"))
alignment.same(COL.taxon("Dinosauria"), dwh.taxon("Dinosauria"))
alignment.same(COL.taxon("Diploglossidae"), dwh.taxon("Diploglossinae"))
alignment.same(COL.taxon("Diplura"), dwh.taxon("Diplura"))
alignment.same(COL.taxon("Dipsadidae"), dwh.taxon("Dipsadinae"))
alignment.same(COL.taxon("Capromyidae"), dwh.taxon("Echimyidae"))
alignment.same(COL.taxon("Echiuroidea"), dwh.taxon("Echiura"))
alignment.same(COL.taxon("Agonoxenidae"), dwh.taxon("Elachistidae"))
alignment.same(COL.taxon("Elasmobranchii"), dwh.taxon("Elasmobranchii"))
alignment.same(COL.taxon("Xenisthmidae"), dwh.taxon("Eleotridae"))
alignment.same(COL.taxon("Anomalopterygidae"), dwh.taxon("Emeidae"))
alignment.same(COL.taxon("Melianthaceae"), dwh.taxon("Francoaceae"))
alignment.same(COL.taxon("Vivianiaceae"), dwh.taxon("Francoaceae"))
alignment.same(COL.taxon("Fulgoroidea"), dwh.taxon("Fulgoromorpha"))
alignment.same(COL.taxon("Diatrymidae"), dwh.taxon("Gastornithidae"))
alignment.same(COL.taxon("Microdesmidae"), dwh.taxon("Gobiidae"))
alignment.same(COL.taxon("Kraemeriidae"), dwh.taxon("Gobiidae"))
alignment.same(COL.taxon("Schindleriidae"), dwh.taxon("Gobiidae"))
alignment.same(COL.taxon("Hesperornidae"), dwh.taxon("Hesperornithidae"))
alignment.same(COL.taxon("Holocephali"), dwh.taxon("Holocephali"))
alignment.same(COL.taxon("Kinorhyncha"), dwh.taxon("Kinorhyncha"))
alignment.same(COL.taxon("Scaridae"), dwh.taxon("Labridae"))
alignment.same(COL.taxon("Odacidae"), dwh.taxon("Labridae"))
alignment.same(COL.taxon("Chrysopolomidae"), dwh.taxon("Limacodidae"))
alignment.same(COL.taxon("Soricomorpha"), dwh.taxon("Lipotyphla"))
alignment.same(COL.taxon("Edgariekiidae"), dwh.taxon("Lophioneuridae"))
alignment.same(COL.taxon("Loricifera"), dwh.taxon("Loricifera"))
alignment.same(COL.taxon("Caesionidae"), dwh.taxon("Lutjanidae"))
alignment.same(COL.taxon("Lymantriidae"), dwh.taxon("Lymantriinae"))
alignment.same(COL.taxon("Mesotaenia doris"), dwh.taxon("Mesotaenia vaninka"))
alignment.same(COL.taxon("Animalia"), dwh.taxon("Metazoa"))
alignment.same(COL.taxon("Liliopsida"), dwh.taxon("Monocots"))
alignment.same(COL.taxon("Musserakis"), dwh.taxon("Musserakis"))
alignment.same(COL.taxon("Myopsida"), dwh.taxon("Myopsida"))
alignment.same(COL.taxon("Myxozoa"), dwh.taxon("Myxozoa"))
alignment.same(COL.taxon("Natricidae"), dwh.taxon("Natricinae"))
alignment.same(COL.taxon("Tetradiclidaceae"), dwh.taxon("Nitrariaceae"))
alignment.same(COL.taxon("Pantheidae"), dwh.taxon("Noctuidae"))
alignment.same(COL.taxon("Medusagynaceae"), dwh.taxon("Ochnaceae"))
alignment.same(COL.taxon("Quiinaceae"), dwh.taxon("Ochnaceae"))
alignment.same(COL.taxon("Metachandidae"), dwh.taxon("Oecophoridae"))
alignment.same(COL.taxon("Oegopsida"), dwh.taxon("Oegopsida"))
alignment.same(COL.taxon("Olacaceae"), dwh.taxon("Olacaceae"))
alignment.same(COL.taxon("Coulaceae"), dwh.taxon("Olacaceae"))
alignment.same(COL.taxon("Erythropalaceae"), dwh.taxon("Olacaceae"))
alignment.same(COL.taxon("Octoknemaceae"), dwh.taxon("Olacaceae"))
alignment.same(COL.taxon("Strombosiaceae"), dwh.taxon("Olacaceae"))
alignment.same(COL.taxon("Ximeniaceae"), dwh.taxon("Olacaceae"))
alignment.same(COL.taxon("Carapidae"), dwh.taxon("Ophidiidae"))
alignment.same(COL.taxon("Arapaimidae"), dwh.taxon("Osteoglossidae"))
alignment.same(COL.taxon("Ostracoda"), dwh.taxon("Ostracoda"))
alignment.same(COL.taxon("Malesherbiaceae"), dwh.taxon("Passifloraceae"))
alignment.same(COL.taxon("Turneraceae"), dwh.taxon("Passifloraceae"))
alignment.same(COL.taxon("Perciliidae"), dwh.taxon("Percichthyidae"))
alignment.same(COL.taxon("Scelionidae"), dwh.taxon("Platygastridae"))
alignment.same(COL.taxon("Pollicipidae"), dwh.taxon("Pollicipedidae"))
alignment.same(COL.taxon("Priapulida"), dwh.taxon("Priapulida"))
alignment.same(COL.taxon("Prostigmata"), dwh.taxon("Prostigmata"))
alignment.same(COL.taxon("Protura"), dwh.taxon("Protura"))
alignment.same(COL.taxon("Pseudoxenodontidae"), dwh.taxon("Pseudoxenodontinae"))
alignment.same(COL.taxon("Bathylutichthyidae"), dwh.taxon("Psychrolutidae"))
alignment.same(COL.taxon("Macropiratidae"), dwh.taxon("Pterophoridae"))
alignment.same(COL.taxon("Anobiidae"), dwh.taxon("Ptinidae"))
alignment.same(COL.taxon("Borthwickiaceae"), dwh.taxon("Resedaceae"))
alignment.same(COL.taxon("Ereuniidae"), dwh.taxon("Rhamphocottidae"))
alignment.same(COL.taxon("Rhodophyta"), dwh.taxon("Rhodophyta"))
alignment.same(COL.taxon("Achiropsettidae"), dwh.taxon("Rhombosoleidae"))
alignment.same(COL.taxon("Cephalorhyncha"), dwh.taxon("Scalidophora"))
alignment.same(COL.taxon("Sepiida"), dwh.taxon("Sepioidea"))
alignment.same(COL.taxon("Sipuncula"), dwh.taxon("Sipuncula"))
alignment.same(COL.taxon("Spirulida"), dwh.taxon("Spirulida"))
alignment.same(COL.taxon("Terebellida"), dwh.taxon("Terebelliformia"))
alignment.same(COL.taxon("Xeninae"), dwh.taxon("Xenidae"))
alignment.same(COL.taxon("Hyperoodontidae"), dwh.taxon("Ziphiidae"))
alignment.same(COL.taxon("Animalia"), dwh.taxon("Metazoa"))
alignment.same(COL.taxon("Fungi"), dwh.taxon("Fungi"))
alignment.same(COL.taxon("Plantae"), dwh.taxon("Archaeplastida"))
alignment.same(COL.taxon("Reptilia"), dwh.taxon("Reptilia"))
alignment.same(COL.taxon("Bdelloidea"), dwh.taxon("Bdelloidea"))
alignment.same(COL.taxon("Euhirudinea"), dwh.taxon("Euhirudinea"))
alignment.same(COL.taxon("Testudinata"), dwh.taxon("Testudinata"))
alignment.same(COL.taxon("Ctenophora"), dwh.taxon("Ctenophora"))
alignment.same(COL.taxon("Chroodactylon"), dwh.taxon("Chroodactylon"))
alignment.same(COL.taxon("Clathromorphum"), dwh.taxon("Clathromorphum"))
alignment.same(COL.taxon("Comasteridae"), dwh.taxon("Comatulidae"))
alignment.same(COL.taxon("Lejolisia"), dwh.taxon("Lejolisia"))
alignment.same(COL.taxon("Asterococcus"), dwh.taxon("Asterococcus"))
alignment.same(COL.taxon("Trasserkidrilus"), dwh.taxon("Tasserkidrilus"))
alignment.same(COL.taxon("Trasserkidrilus harmani"), dwh.taxon("Varichaetadrilus harmani"))
alignment.same(COL.taxon("Varichaetadrilus"), dwh.taxon("Varichaetadrilus"))
alignment.same(COL.taxon("Trasserkidrilus kessleri"), dwh.taxon("Tasserkidrilus kessleri"))
alignment.same(COL.taxon("Trasserkidrilus superiorensis"), dwh.taxon("Tasserkidrilus superiorensis"))
alignment.same(COL.taxon("Bothrioneuron"), dwh.taxon("Bothrioneurum"))
alignment.same(COL.taxon("Bothrioneuron veejdovskyanum"), dwh.taxon("Bothrioneurum vejdovskyanum"))
alignment.same(COL.taxon("Bothrioneuron iris"), dwh.taxon("Bothrioneuron iris"))
alignment.same(COL.taxon("Piquetiella"), dwh.taxon("Piguetiella"))
alignment.same(COL.taxon("Piquetiella blanci"), dwh.taxon("Piguetiella blanci"))
dwh.align(alignment)
dwh.merge(alignment)

for root in Taxonomy.roots(dwh):
	print root

dwh.dump('test/')
